version: '3'

services:

  api:
    build: api/.
    container_name: api
    environment:
      - SERVNAME=201404104
    ports:
    - 5002:5002
    networks:
      service_network:

networks:

    service_network:
        driver: bridge

